spring:
  application:
    name: hyeyum
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hyeyum}
    username: ${SPRING_DATASOURCE_USERNAME:hyeyum}
    password: ${SPRING_DATASOURCE_PASSWORD:hyeyum}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api
