create table if not exists public.btp_infra_hub (
    hub_id bigint generated by default as identity primary key,
    hub_name varchar(100) not null,
    hub_kind varchar(20) not null,
    center_name varchar(150),
    summary text,
    address varchar(300),
    district_name varchar(50),
    tel varchar(50),
    latitude numeric(10, 7),
    longitude numeric(10, 7),
    image_url text,
    space_url text,
    directions_url text,
    source_url text not null,
    display_order integer not null,
    active boolean not null default true,
    constraint uk_btp_infra_hub_name unique (hub_name)
);

comment on table public.btp_infra_hub is 'BTP official infrastructure hub master crawled from BTP campus guide';
comment on column public.btp_infra_hub.hub_kind is 'Hub kind: CAMPUS or BRANCH';
comment on column public.btp_infra_hub.center_name is 'Representative center/organization name shown in BTP guide';
comment on column public.btp_infra_hub.summary is 'Official detail text shown in BTP campus guide modal';
comment on column public.btp_infra_hub.source_url is 'Official source page URL';

create table if not exists public.btp_infra_hub_facility (
    facility_id bigint generated by default as identity primary key,
    hub_id bigint not null references public.btp_infra_hub(hub_id) on delete cascade,
    site_name varchar(200),
    building_no varchar(50),
    building_name varchar(200) not null,
    gross_floor_area varchar(100),
    floors varchar(50),
    purpose text,
    display_order integer not null default 0
);

comment on table public.btp_infra_hub_facility is 'Facility details shown in BTP official hub modal';

create table if not exists public.btp_infra_hub_alias (
    alias_id bigint generated by default as identity primary key,
    hub_id bigint not null references public.btp_infra_hub(hub_id) on delete cascade,
    match_keyword varchar(200) not null,
    priority integer not null default 0,
    constraint uk_btp_infra_hub_alias unique (hub_id, match_keyword)
);

comment on table public.btp_infra_hub_alias is 'Keyword rules for joining btp_equipment.location_name to official BTP hubs';

insert into public.btp_infra_hub (
    hub_name, hub_kind, center_name, summary, address, district_name, tel,
    latitude, longitude, image_url, space_url, directions_url, source_url, display_order, active
)
values
    ('지사단지', 'CAMPUS', '부산테크노파크 본부', '부산테크노파크 본부(경영지원실, 미래신산업단, 첨단주력산업단) - 기업지원 인프라 및 입주공간', '부산광역시 강서구 과학산단1로 60번길', '강서구', '051-974-9000', 35.1451478, 128.8271768, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_jisa_01.jpg', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN026', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN073', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 1, true),
    ('엄궁단지', 'CAMPUS', '기업지원단', '기업지원단 - 기업지원 사업 통합 관리, 입주공간', '부산광역시 사상구 엄궁로 70-16 (B108호)', '사상구', '051-320-3527', 35.1240024, 128.9747882, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_umgung_01.jpg', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN027', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN074', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 2, true),
    ('장전단지', 'CAMPUS', '전력반도체센터', '전력반도체센터 - 반도체 소재개발 인프라, 장비 지원', '부산광역시 금정구 부산대학로63번길2(부산대학교 내)', '금정구', '051-516-3989', 35.2304340, 129.0839729, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_jangjeon_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN076', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 3, true),
    ('일광단지', 'CAMPUS', '라이프센터', '라이프센터 - 커피, 화장품관련 기업지원, 입주공간', '부산광역시 기장군 일광면 횡계길 7', '기장군', '051-720-8900', 35.2728860, 129.2265740, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_ilgwang_01.jpg', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN028', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN075', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 4, true),
    ('영도단지', 'CAMPUS', '해양ICT센터', '해양ICT센터 - 해운항만물류, 수리조선산업, 데이터 기반 해양ICT산업 기업지원, 입주공간', '부산광역시 영도구 해양로 435-1', '영도구', '051-991-8403', 35.0874657, 129.0725519, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_dongsam_01.jpg', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN029', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN077', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 5, true),
    ('미음단지', 'CAMPUS', '우주항공 · 소재센터', '우주항공 · 소재센터 - 첨단융복합소재산업 기업지원 인프라 및 입주공간', '부산광역시 강서구 미음산단5로 41번길 21', '강서구', '051-831-7824', 35.1560219, 128.8590849, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_mieum_01.jpg', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN030', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN078', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 6, true),
    ('장안단지', 'CAMPUS', '전력반도체센터', '전력반도체센터 - 신뢰성평가 인프라, 장비 지원, 입주공간', '부산광역시 기장군 장안읍 의과학로 42', '기장군', '051-728-6013', 35.3266926, 129.2499535, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_jangan_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN079', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 7, true),
    ('다대단지', 'CAMPUS', '바이오헬스센터', '바이오헬스센터 - 기기 안전성 시험인증, 전자의료기기 사용적합성평가', '부산광역시 사하구 윤공단로 14번길100', '사하구', '051-320-3664', 35.0571873, 128.9698628, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_dadae_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN120', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 8, true),
    ('개금단지', 'CAMPUS', '슈비즈센터', '슈비즈센터 - 한국신발관 전시홍보관 및 역사관, 입주공간', '부산광역시 부산진구 백양대로 227', '부산진구', '051-898-3038', 35.1590659, 129.0312463, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_gaegeum_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN181', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 9, true),
    ('범일단지', 'CAMPUS', '섬유패션센터', '섬유패션센터 - 범일동 인근 의류제조 소공인 장비지원, 시설대관, 입주공간', '부산광역시 동구 조방로 38번길 3-1', '동구', '051-631-2050', 35.1404328, 129.0618737, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_beomil_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN182', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 10, true),
    ('감전단지', 'CAMPUS', '신발허브센터', '신발허브센터 - 메이커스페이스 운영 및 기업지원, 입주공간', '부산광역시 사상구 낙동대로943번길 235', '사상구', '051-317-8501', 35.1380636, 128.9670199, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_gamjeon_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN183', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 11, true),
    ('장림단지', 'CAMPUS', '블루푸드센터', '블루푸드센터 - 수산식품산업육성지원, 해양수산산업창업투자지원, 입주공간', '부산광역시 사하구 장림로91', '사하구', '051-320-3601', 35.0839232, 128.9796797, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_jangnim_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN185', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 12, true),
    ('녹산단지', 'CAMPUS', '신발인증센터', '신발인증센터 - 성능평가 테스트베드 및 입주공간', '부산광역시 강서구 녹산산단 382로 14번길 55', '강서구', '051-979-7100', 35.0878286, 128.8559116, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_noksan_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN184', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 13, true),
    ('생곡단지', 'CAMPUS', '모빌리티센터', '모빌리티센터 - 지역 자동차 부품기업의 미래차 전환 지원', '부산광역시 강서구 미음국제8로 108', '강서구', '051-974-9216', 35.1305900, 128.8804026, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_sgok_01.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN192', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 14, true),
    ('수안단지', 'CAMPUS', '재난안전산업센터', '재난안전산업센터 - 안전산업 관련 제품 시험평가 테스트베드 및 입주공간', '부산광역시 동래구 온천천로203', '동래구', '051-558-5415', 35.2173124, 129.0846862, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/branch_suan_01-2.jpg', null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN193', 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 15, true),
    ('센텀분소', 'BRANCH', 'DX데이터센터', 'DX데이터센터 - 데이터산업육성 및 기업지원', '부산광역시 해운대구 센텀동로 45(웹스빌딩 5,7층)', '해운대구', '051-747-6352', 35.1732210, 129.1304488, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/of01_01.jpg', null, null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 16, true),
    ('양정분소', 'BRANCH', '정책기획단', '정책기획단', '부산광역시 부산진구 진연로9번길39(엔에스타워 3층)', '부산진구', null, 35.1709000, 129.0699000, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/of04_01.jpg', null, null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 17, true),
    ('문현분소', 'BRANCH', '블록체인센터', '블록체인센터 - 부산 블록체인 기업 육성 및 입주공간', '부산광역시 남구 문현금융로40, 부산국제금융센터(8~9층, 21~22층)', '남구', '051-923-8323', 35.1464139, 129.0648500, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/of07_01.jpg', null, null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 18, true),
    ('명륜분소', 'BRANCH', '지산학DX단', '지산학DX단 - 지역인재양성 및 대학혁신 체계 구축', '부산광역시 동래구 온천천로 71, 반도빌딩 3층', '동래구', '051-866-5363', 35.2049000, 129.0803000, 'https://www.btp.or.kr/resources/homepage/kor/_Img/Contents/branch/of08_01.jpg', null, null, 'https://www.btp.or.kr/kor/CMS/Contents/Contents.do?mCode=MN066', 19, true)
on conflict (hub_name) do update set
    hub_kind = excluded.hub_kind,
    center_name = excluded.center_name,
    summary = excluded.summary,
    address = excluded.address,
    district_name = excluded.district_name,
    tel = excluded.tel,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    image_url = excluded.image_url,
    space_url = excluded.space_url,
    directions_url = excluded.directions_url,
    source_url = excluded.source_url,
    display_order = excluded.display_order,
    active = excluded.active;

delete from public.btp_infra_hub_facility
where hub_id in (select hub_id from public.btp_infra_hub);

with facility_seed(hub_name, site_name, building_no, building_name, gross_floor_area, floors, purpose, display_order) as (
    values
        ('지사단지', '지사단지 A부지 / (1276번지) 부산광역시 강서구 과학산단1로 60번길 31', '1', '지사단지1동', '4,895.99', '3F', '입주공간(1F_공장동)', 1),
        ('지사단지', '지사단지 A부지', '2', '지사단지2A동', '2,998.26', 'B1/4F', '구내식당/입주공간', 2),
        ('지사단지', '지사단지 A부지', null, '지사단지2B동', '5,458.65', '4F', '입주공간', 3),
        ('지사단지', '지사단지 A부지', '3', '지사단지3동', '1,942.16', '2F', '에너지테크센터', 4),
        ('지사단지', '지사단지 B부지 / (1274번지) 부산광역시 강서구 과학산단1로 60번길 30', '4', '지사단지4동', '6,580.36', 'B1/5F', '모빌리티센터/융합부품센터/에너지테크센터/입주공간', 5),
        ('지사단지', '지사단지 B부지', '5', '지사단지5동', '4,050.11', '3F', '융합부품센터/입주공간', 6),
        ('지사단지', '지사단지 B부지', '6', '지사단지6동', '2,799.64', '2F', '모빌리티센터/입주공간', 7),
        ('지사단지', '지사단지 B부지', '7', '지사단지7동', '2,241.35', '6F', '융합부품센터/입주공간', 8),
        ('지사단지', '지사단지 B부지', '8', '지사단지8동', '3,382.35', '3F', '입주공간', 9),
        ('지사단지', '지사단지 B부지', '9', '지사단지9동', '6,692.29', '4F', '우주항공소재센터, 융합부품센터 시험인증실/입주공간', 10),
        ('지사단지', '지사단지 B부지', '10', '하이테크부품소재 연구지원동', '4,789.05', '3F', '한국기초과학지원연구원', 11),
        ('지사단지', '지사단지 B부지', '11', '하이테크부품소재 연구지원동', '430.00', '1F', '한국기초과학지원연구원', 12),
        ('지사단지', '지사단지 C부지 / (1277) 부산광역시 강서구 과학산단1로 60번길 32', '12', '지사단지12동', '4,989.74', '5F', '우주항공소재센터/입주공간', 13),
        ('지사단지', '지사단지 C부지', '13', '지사단지13동', '12,633.66', 'B1/9F', '경영지원실/감사실/휴게실/체력단련실/입주공간', 14),
        ('엄궁단지', null, null, '부산테크노파크 엄궁단지', '10,569.70', 'B2/5F', '기업지원단/입주공간', 1),
        ('장전단지', null, null, 'MEMS/NANO클린룸동', '2,003.87', '3F', '전력반도체센터(반도체소재개발)', 1),
        ('일광단지', null, null, '기업지원동', '4,428.49', '4F', '라이프센터/입주공간', 1),
        ('일광단지', null, null, '기업설비지원 A동', '1,250.79', '1F', '입주공간', 2),
        ('일광단지', null, null, '기업설비지원 B동', '1,246.69', '1F', '입주공간', 3),
        ('일광단지', null, null, '생산설비동', '1,746.23', '2F', '부산화장품공장, 장비', 4),
        ('영도단지', null, null, '해양물류산업센터', '4,106.18', '3F', '해양ICT센터/입주공간 해양신산업 플랫폼', 1),
        ('미음단지', null, null, '해양융복합소재센터 본관동', '5,372.80', 'B1/4F', '우주항공 · 소재센터/입주공간', 1),
        ('미음단지', null, null, '해양융복합소재센터 화재실험동', '404.59', '1F', '센터 시험실', 2),
        ('미음단지', null, null, '해양융복합소재센터 종합시험동', '541.26', '1F', '센터 시험실', 3),
        ('장안단지', null, null, '전력반도체센터', '5,793.62', '4F', '전력반도체센터(신뢰성평가)', 1),
        ('다대단지', null, null, '부산테크노파크 다대단지', '3,894', 'B1/5F', '바이오헬스센터, 리빙랩, 건강데이터 구축 및 제품 유효성 검증, 의료기기 사용적합성평가 및 사용성평가, 역학시험검사', 1),
        ('개금단지', null, null, '한국신발관', '4,141.42', 'B1/7F', '신발전시관(홍보관), 입주공간, 인력양성교육장', 1),
        ('범일단지', null, null, '범일의류제조지원센터', '591.51', '4F', '사무실, 입주공간, 교육실', 1),
        ('감전단지', null, null, '지원동', '3,072.64', '3F', '신발허브센터 사무공간, 노을정원', 1),
        ('감전단지', null, null, '공장동', '17,411.44', '6F', '입주지원, 하늘정원', 2),
        ('장림단지', null, null, '부산씨푸드플랫폼', '5,260.63㎡ (공용 2,321.25㎡, 전용 2,939.38㎡)', '지하1F, 4F', '임대공간(26실), 연구분석/회의실 등 공용시설', 1),
        ('녹산단지', null, null, '신발산업진흥센터', '10,945.53', '3F', '신발인증센터/입주공간', 1),
        ('녹산단지', null, null, '녹산협업화사업장', '12,486', '3F', '입주공간', 2),
        ('생곡단지', null, null, '전기차E-파워트레인', '1217.58', '1F', '모빌리티센터 시험실', 1),
        ('생곡단지', null, null, '전기차E-파워트레인', '251.84', '2F', '모빌리티센터 시험실, 옥외전기실 등', 2),
        ('수안단지', null, null, '재난안전산업지원센터', '1972.13', '5F', '재난안전산업센터/시험장비/입주공간', 1)
)
insert into public.btp_infra_hub_facility (
    hub_id, site_name, building_no, building_name, gross_floor_area, floors, purpose, display_order
)
select
    hub.hub_id,
    seed.site_name,
    seed.building_no,
    seed.building_name,
    seed.gross_floor_area,
    seed.floors,
    seed.purpose,
    seed.display_order
from facility_seed seed
join public.btp_infra_hub hub on hub.hub_name = seed.hub_name;

with alias_seed(hub_name, match_keyword, priority) as (
    values
        ('지사단지', '지사단지', 100),
        ('지사단지', '부산테크노파크 자동차부품기술지원센터', 90),
        ('지사단지', '부산테크노파크 기계부품소재기술지원센터', 90),
        ('지사단지', '부산테크노파크 스마트전자부품기술지원센터', 90),
        ('지사단지', '지능형기계부품센터', 90),
        ('지사단지', '우주항공방산센터(지사)', 90),
        ('지사단지', '전자파시험동', 80),
        ('지사단지', '자동차부품기술협력센터', 80),
        ('지사단지', '차세대열교환기센터', 80),
        ('지사단지', 'POST-BI동', 80),
        ('엄궁단지', '엄궁단지', 100),
        ('엄궁단지', '엄궁센터', 90),
        ('엄궁단지', '엄궁지사', 90),
        ('장전단지', '장전단지', 100),
        ('장전단지', '파워반도체상용화센터', 90),
        ('장전단지', 'MEMS/NANO부품생산센터', 90),
        ('장전단지', '클린룸동', 80),
        ('장전단지', '파워반도체동', 80),
        ('일광단지', '일광단지', 100),
        ('일광단지', '해양생물산업육성센터', 90),
        ('영도단지', '영도단지', 100),
        ('영도단지', '해양ICT센터', 90),
        ('영도단지', '해양물류산업센터', 90),
        ('영도단지', '스마트수리조선지원센터', 90),
        ('영도단지', '종합물류경영기술지원센터', 90),
        ('미음단지', '미음단지', 100),
        ('미음단지', '해양융복합소재센터', 90),
        ('미음단지', '우주항공방산센터(미음)', 90),
        ('미음단지', '첨단융복합소재센터', 90),
        ('미음단지', '종합시험동', 80),
        ('미음단지', '화재시험동', 80),
        ('장안단지', '장안단지', 100),
        ('장안단지', '전력반도체센터', 90),
        ('장안단지', '신뢰성시험실', 80),
        ('다대단지', '다대단지', 100),
        ('다대단지', '의료산업기술지원센터', 90),
        ('다대단지', '고령친화산업화지원센터', 90),
        ('다대단지', '황노화산업지원센터', 90),
        ('개금단지', '개금단지', 100),
        ('개금단지', '한국신발관', 90),
        ('범일단지', '범일단지', 100),
        ('범일단지', '범일의류제조지원센터', 90),
        ('감전단지', '감전단지', 100),
        ('감전단지', '첨단신발융합허브센터', 90),
        ('장림단지', '장림단지', 100),
        ('장림단지', '부산씨푸드플랫폼', 90),
        ('녹산단지', '녹산단지', 100),
        ('녹산단지', '신발패션인증센터', 90),
        ('녹산단지', '신발인증센터', 90),
        ('생곡단지', '생곡단지', 100),
        ('생곡단지', '전기차허브센터', 90),
        ('생곡단지', '모빌리티센터 생곡단지', 90),
        ('수안단지', '수안단지', 100),
        ('수안단지', '안전산업센터', 90),
        ('수안단지', '재난안전산업지원센터', 90),
        ('센텀분소', '센텀분소', 100),
        ('센텀분소', 'DX데이터센터', 90),
        ('양정분소', '양정분소', 100),
        ('양정분소', '정책기획단', 90),
        ('문현분소', '문현분소', 100),
        ('문현분소', '블록체인센터', 90),
        ('명륜분소', '명륜분소', 100),
        ('명륜분소', '지산학DX단', 90)
)
insert into public.btp_infra_hub_alias (hub_id, match_keyword, priority)
select hub.hub_id, seed.match_keyword, seed.priority
from alias_seed seed
join public.btp_infra_hub hub on hub.hub_name = seed.hub_name
on conflict (hub_id, match_keyword) do update set
    priority = excluded.priority;

create index if not exists idx_btp_infra_hub_display_order
    on public.btp_infra_hub (active, display_order);

create index if not exists idx_btp_infra_hub_alias_keyword
    on public.btp_infra_hub_alias (match_keyword);

create index if not exists idx_btp_infra_hub_facility_hub_order
    on public.btp_infra_hub_facility (hub_id, display_order);
