--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: btp_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.btp_equipment (
    id bigint NOT NULL,
    category_large character varying(100),
    category_middle character varying(100),
    category_small character varying(100),
    description text,
    equipment_name character varying(255) NOT NULL,
    equipment_name_en character varying(255),
    image_url text,
    latitude numeric(10,7),
    location_name character varying(255),
    longitude numeric(10,7),
    source_equipment_seq integer NOT NULL
);


--
-- Name: COLUMN btp_equipment.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.id IS '시퀀스//장비 내부 식별자';


--
-- Name: COLUMN btp_equipment.category_large; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.category_large IS '표준분류 대분류';


--
-- Name: COLUMN btp_equipment.category_middle; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.category_middle IS '표준분류 중분류';


--
-- Name: COLUMN btp_equipment.category_small; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.category_small IS '표준분류 소분류';


--
-- Name: COLUMN btp_equipment.description; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.description IS '장비 설명';


--
-- Name: COLUMN btp_equipment.equipment_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.equipment_name IS '장비명';


--
-- Name: COLUMN btp_equipment.equipment_name_en; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.equipment_name_en IS '영문 장비명';


--
-- Name: COLUMN btp_equipment.image_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.image_url IS '장비 이미지 URL';


--
-- Name: COLUMN btp_equipment.latitude; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.latitude IS '설치장소 위도';


--
-- Name: COLUMN btp_equipment.location_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.location_name IS '설치장소명';


--
-- Name: COLUMN btp_equipment.longitude; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.longitude IS '설치장소 경도';


--
-- Name: COLUMN btp_equipment.source_equipment_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_equipment.source_equipment_seq IS '원본 장비 순번(eq_seq)';


--
-- Name: btp_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.btp_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.btp_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: btp_support_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.btp_support_history (
    support_history_id bigint NOT NULL,
    budget_program_name character varying(1000),
    code character varying(20),
    company_id integer,
    district_name character varying(20),
    end_date date,
    established_year integer,
    field character varying(255),
    industry_code character varying(20),
    main_product character varying(1000),
    province_name character varying(20),
    selected_date date,
    selection_result character varying(20),
    source_hash character varying(64) NOT NULL,
    start_date date,
    support_amount integer,
    support_category character varying(20),
    support_detail character varying(1000),
    support_item character varying(1000),
    support_type character varying(20),
    support_year integer
);


--
-- Name: COLUMN btp_support_history.support_history_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_history_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN btp_support_history.budget_program_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.budget_program_name IS '부산TP 예산서의 사업명//예시) 친환경미래에너지마케팅사업';


--
-- Name: COLUMN btp_support_history.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.code IS '코드//예시) B1_311';


--
-- Name: COLUMN btp_support_history.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN btp_support_history.district_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.district_name IS '기초//예시) 동구';


--
-- Name: COLUMN btp_support_history.end_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.end_date IS '종료일//예시) 2022-03-31';


--
-- Name: COLUMN btp_support_history.established_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.established_year IS '설립연도//예시) 1999';


--
-- Name: COLUMN btp_support_history.industry_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.industry_code IS '업종코드//예시) 25929';


--
-- Name: COLUMN btp_support_history.main_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.main_product IS '주생산품//예시) 관제장비 및 주변장치';


--
-- Name: COLUMN btp_support_history.province_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.province_name IS '광역//예시) 부산';


--
-- Name: COLUMN btp_support_history.selected_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.selected_date IS '선정일//예시) 2022-08-26';


--
-- Name: COLUMN btp_support_history.selection_result; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.selection_result IS '선정결과//예시) 지원대상';


--
-- Name: COLUMN btp_support_history.source_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.source_hash IS '원본 데이터 중복 방지를 위한 해시값';


--
-- Name: COLUMN btp_support_history.start_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.start_date IS '시작일//예시) 2022-09-01';


--
-- Name: COLUMN btp_support_history.support_amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_amount IS '지원금(천원)//예시)  13,400';


--
-- Name: COLUMN btp_support_history.support_category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_category IS '지원구분(주요지원)//예시) 전시회';


--
-- Name: COLUMN btp_support_history.support_detail; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_detail IS '지원구분(추가정보)//예시) 마케팅';


--
-- Name: COLUMN btp_support_history.support_item; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_item IS '지원품목//예시) 베트남Entech, 마케팅조사분석';


--
-- Name: COLUMN btp_support_history.support_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_type IS '사업유형//예시) 사업화지원';


--
-- Name: COLUMN btp_support_history.support_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_history.support_year IS '연도//3개의 시트를 합칠 생각 (예시) 2022';


--
-- Name: btp_support_history_support_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.btp_support_history ALTER COLUMN support_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.btp_support_history_support_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: btp_support_program; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.btp_support_program (
    support_program_id bigint NOT NULL,
    announcement_url character varying(20),
    budget_program_name character varying(1000),
    code character varying(20) NOT NULL,
    department_name character varying(20),
    end_date date,
    local_government_name character varying(20),
    program_category character varying(20),
    program_summary character varying(1000),
    program_year integer,
    start_date date,
    support_type character varying(20)
);


--
-- Name: COLUMN btp_support_program.support_program_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.support_program_id IS '시퀀스//지원사업 내부 식별자';


--
-- Name: COLUMN btp_support_program.announcement_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.announcement_url IS '기업 마당 공고문 정보//PDF 링크들을 담을 예정';


--
-- Name: COLUMN btp_support_program.budget_program_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.budget_program_name IS '부산TP 예산서의 사업명//예시) 비대면솔루션지원사업';


--
-- Name: COLUMN btp_support_program.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.code IS '예시) A1_301';


--
-- Name: COLUMN btp_support_program.department_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.department_name IS '부처명//예시) 산업부';


--
-- Name: COLUMN btp_support_program.end_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.end_date IS '종료일//예시) 2022-01-02';


--
-- Name: COLUMN btp_support_program.local_government_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.local_government_name IS '지자체//예시) 부산시';


--
-- Name: COLUMN btp_support_program.program_category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.program_category IS '사업구분//예시) 기업지원';


--
-- Name: COLUMN btp_support_program.program_summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.program_summary IS '주요내용//예시) 경제 활성화';


--
-- Name: COLUMN btp_support_program.program_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.program_year IS '연도// 3개의 시트를 합칠 생각 (예시) 2022';


--
-- Name: COLUMN btp_support_program.start_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.start_date IS '시작일//예시) 2022-01-01';


--
-- Name: COLUMN btp_support_program.support_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.btp_support_program.support_type IS '사업유형//예시) 패키지지원';


--
-- Name: btp_support_program_support_program_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.btp_support_program ALTER COLUMN support_program_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.btp_support_program_support_program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    company_id integer NOT NULL,
    address character varying(1000),
    ai_one_line_summary text,
    ai_summary text,
    business_entity_type character varying(20),
    business_registration_number character varying(20),
    closed_date date,
    closure_type character varying(20),
    company_name character varying(20),
    company_size character varying(20),
    company_status character varying(20),
    company_type character varying(20),
    cost_of_sales_ratio double precision,
    debt_ratio double precision,
    employee_turnover_rate double precision,
    employment_growth_rate double precision,
    employment_peak_index double precision,
    established_date date,
    government_rnd_dependency double precision,
    has_research_lab boolean,
    has_rnd_department boolean,
    industry_brief text,
    industry_description text,
    industry_name character varying(1000),
    is_closed boolean,
    is_innobiz boolean,
    is_mainbiz boolean,
    is_materials_company boolean,
    is_nep_certified boolean,
    is_net_certified boolean,
    is_venture_company boolean,
    ksic_code character varying(20),
    listing_status character varying(20),
    main_product character varying(1000),
    reference_date date,
    region_name character varying(20),
    research_lab_registered_date date,
    researcher_count integer,
    rnd_department_registered_date date,
    sales_growth_rate double precision,
    supported_sales_growth_rate double precision
);


--
-- Name: COLUMN company.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company.address; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.address IS '위치//우리가 가공해야 함 (예시)';


--
-- Name: COLUMN company.ai_one_line_summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.ai_one_line_summary IS 'AI 한줄 요약//AI로 미리 저장해둘 것 (예시)';


--
-- Name: COLUMN company.ai_summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.ai_summary IS 'AI 3줄 요약//AI로 미리 저장해둘 것 (예시)';


--
-- Name: COLUMN company.business_entity_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.business_entity_type IS '기업유형(법입/개인)//예시) 법인기업';


--
-- Name: COLUMN company.business_registration_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.business_registration_number IS '사업자등록번호//우리가 만들어야함 (예시)';


--
-- Name: COLUMN company.closed_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.closed_date IS '폐업일자//예시)';


--
-- Name: COLUMN company.closure_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.closure_type IS '휴폐업구분//예시) 부가가치세 일반과세자';


--
-- Name: COLUMN company.company_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.company_name IS '기업명//우리가 만들어야함 (예시)';


--
-- Name: COLUMN company.company_size; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.company_size IS '기업유형(법입/개인)//예시) 소상공인';


--
-- Name: COLUMN company.company_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.company_status IS '기업상태//예시) 정상';


--
-- Name: COLUMN company.company_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.company_type IS '기업형태 (주식/개인)//예시) 주식회사';


--
-- Name: COLUMN company.cost_of_sales_ratio; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.cost_of_sales_ratio IS '매출원가율//계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.debt_ratio; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.debt_ratio IS '부채비율/계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.employee_turnover_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.employee_turnover_rate IS '고용 회전율//계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.employment_growth_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.employment_growth_rate IS '고용 성장성//계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.employment_peak_index; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.employment_peak_index IS '고용 괴리지수//계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.established_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.established_date IS '설립일자//예시) 20100202';


--
-- Name: COLUMN company.government_rnd_dependency; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.government_rnd_dependency IS '정부 R&D 의존도//계산식을 적용해서 미리 넣어둘 생각(없을 수 있음) (예시)';


--
-- Name: COLUMN company.has_research_lab; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.has_research_lab IS '기업부설연구소 유무//예시) 여';


--
-- Name: COLUMN company.has_rnd_department; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.has_rnd_department IS '연구개발전담부서 유무//예시) 부';


--
-- Name: COLUMN company.industry_brief; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.industry_brief IS '업종 맥락 브리핑//AI로 미리 저장해둘 것 (예시)';


--
-- Name: COLUMN company.industry_description; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.industry_description IS '업종명 (11차) 상세정보//보민님이 찾은 정보를 넣을 생각 (예시)';


--
-- Name: COLUMN company.industry_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.industry_name IS '업종명 (11차)//예시) 그 외 기타 의료용품 및 의약 관련제품 제조업';


--
-- Name: COLUMN company.is_closed; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_closed IS '휴폐업여부//예시) N';


--
-- Name: COLUMN company.is_innobiz; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_innobiz IS '이노비즈 여부//예시) 유';


--
-- Name: COLUMN company.is_mainbiz; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_mainbiz IS '메인비즈 여부//예시) 유';


--
-- Name: COLUMN company.is_materials_company; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_materials_company IS '소재부품 여부//예시) 유';


--
-- Name: COLUMN company.is_nep_certified; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_nep_certified IS 'NEP 여부//예시) 유';


--
-- Name: COLUMN company.is_net_certified; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_net_certified IS 'NET 여부//예시) 유';


--
-- Name: COLUMN company.is_venture_company; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.is_venture_company IS '벤처기업 여부//예시) 유';


--
-- Name: COLUMN company.ksic_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.ksic_code IS 'KSIC코드 (11차)//예시) C21309';


--
-- Name: COLUMN company.listing_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.listing_status IS '기업공개(코스피,코스닥)//예시) 일반법인';


--
-- Name: COLUMN company.main_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.main_product IS '주요제품//예시) 골이식재_덴탈';


--
-- Name: COLUMN company.reference_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.reference_date IS '조회일자//예시) 20260630';


--
-- Name: COLUMN company.region_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.region_name IS '지역//예시) 부산';


--
-- Name: COLUMN company.research_lab_registered_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.research_lab_registered_date IS '기업부설연구소 등록일//예시) 20161221';


--
-- Name: COLUMN company.researcher_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.researcher_count IS '최근 연구원수//예시) 3';


--
-- Name: COLUMN company.rnd_department_registered_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.rnd_department_registered_date IS '연구개발전담부서 등록일//예시) 20201231';


--
-- Name: COLUMN company.sales_growth_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.sales_growth_rate IS '매출 성장성//계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: COLUMN company.supported_sales_growth_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company.supported_sales_growth_rate IS '지원 기업 매출 변화율/계산식을 적용해서 미리 넣어둘 생각 (예시)';


--
-- Name: company_business_purpose; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_business_purpose (
    business_purpose_id bigint NOT NULL,
    business_purpose character varying(1000),
    company_id integer,
    display_order integer,
    registered_date date
);


--
-- Name: COLUMN company_business_purpose.business_purpose_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_business_purpose.business_purpose_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_business_purpose.business_purpose; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_business_purpose.business_purpose IS '사업목적항목내용//예시) 1. 환경엔지니어링';


--
-- Name: COLUMN company_business_purpose.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_business_purpose.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_business_purpose.display_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_business_purpose.display_order IS '순서//예시) 1';


--
-- Name: COLUMN company_business_purpose.registered_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_business_purpose.registered_date IS '등기일자//예시) 20100202';


--
-- Name: company_business_purpose_business_purpose_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_business_purpose ALTER COLUMN business_purpose_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_business_purpose_business_purpose_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_employment_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_employment_statistics (
    employment_statistics_id bigint NOT NULL,
    average_salary integer,
    company_id integer,
    employee_count integer,
    pension_new_hire_count integer,
    pension_retiree_count integer,
    pension_subscriber_count integer,
    year integer
);


--
-- Name: COLUMN company_employment_statistics.employment_statistics_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.employment_statistics_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_employment_statistics.average_salary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.average_salary IS '1인평균년간급여(합계)_단위:원//예시)  41,123,704';


--
-- Name: COLUMN company_employment_statistics.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_employment_statistics.employee_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.employee_count IS '종업원수//예시) 1';


--
-- Name: COLUMN company_employment_statistics.pension_new_hire_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.pension_new_hire_count IS '국민연금 취업자수//예시) 1';


--
-- Name: COLUMN company_employment_statistics.pension_retiree_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.pension_retiree_count IS '국민연금 퇴직자수//예시) 1';


--
-- Name: COLUMN company_employment_statistics.pension_subscriber_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.pension_subscriber_count IS '국민연금 가입자수//예시) 1';


--
-- Name: COLUMN company_employment_statistics.year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_employment_statistics.year IS '연도//예시) 2022';


--
-- Name: company_employment_statistics_employment_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_employment_statistics ALTER COLUMN employment_statistics_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_employment_statistics_employment_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_financial_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_financial_statistics (
    financial_statistics_id bigint NOT NULL,
    company_id integer,
    cost_of_sales integer,
    net_income integer,
    operating_income integer,
    operating_margin double precision,
    paid_in_capital integer,
    research_and_development_expense integer,
    sales_amount integer,
    total_assets integer,
    total_equity integer,
    total_liabilities integer,
    year integer
);


--
-- Name: COLUMN company_financial_statistics.financial_statistics_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.financial_statistics_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_financial_statistics.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_financial_statistics.cost_of_sales; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.cost_of_sales IS '매출원가//예시)  24,399,948';


--
-- Name: COLUMN company_financial_statistics.net_income; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.net_income IS '당기순이익손실//예시) -2,820,077';


--
-- Name: COLUMN company_financial_statistics.operating_income; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.operating_income IS '영업이익손실//예시) -540,086';


--
-- Name: COLUMN company_financial_statistics.operating_margin; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.operating_margin IS '영업이익률//예시) -53.17';


--
-- Name: COLUMN company_financial_statistics.paid_in_capital; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.paid_in_capital IS '납입자본금//예시)  950,000';


--
-- Name: COLUMN company_financial_statistics.research_and_development_expense; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.research_and_development_expense IS '연구개발비//예시)  773,482';


--
-- Name: COLUMN company_financial_statistics.sales_amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.sales_amount IS '매출액//예시)  28,018,841';


--
-- Name: COLUMN company_financial_statistics.total_assets; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.total_assets IS '자산총계//예시)  4,281,095';


--
-- Name: COLUMN company_financial_statistics.total_equity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.total_equity IS '자본총계//예시)  205,024';


--
-- Name: COLUMN company_financial_statistics.total_liabilities; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.total_liabilities IS '부채총계//예시)  8,355,775';


--
-- Name: COLUMN company_financial_statistics.year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_financial_statistics.year IS '연도//예시) 2022';


--
-- Name: company_financial_statistics_financial_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_financial_statistics ALTER COLUMN financial_statistics_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_financial_statistics_financial_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_industry_benchmark_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_industry_benchmark_mapping (
    company_id integer NOT NULL,
    bok_industry_code character varying(50),
    ksic_code character varying(20),
    mapping_level character varying(50),
    mapping_status character varying(50),
    unavailable_reason character varying(100),
    updated_at timestamp(6) without time zone,
    usable_for_operating_margin_benchmark boolean,
    usable_for_revenue_benchmark boolean
);


--
-- Name: COLUMN company_industry_benchmark_mapping.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.company_id IS 'Company ID';


--
-- Name: COLUMN company_industry_benchmark_mapping.bok_industry_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.bok_industry_code IS 'Mapped BOK industry code';


--
-- Name: COLUMN company_industry_benchmark_mapping.ksic_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.ksic_code IS 'KSIC code copied from company';


--
-- Name: COLUMN company_industry_benchmark_mapping.mapping_level; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.mapping_level IS 'Mapping level';


--
-- Name: COLUMN company_industry_benchmark_mapping.mapping_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.mapping_status IS 'Mapping status';


--
-- Name: COLUMN company_industry_benchmark_mapping.unavailable_reason; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.unavailable_reason IS 'Reason when benchmark mapping cannot be used';


--
-- Name: COLUMN company_industry_benchmark_mapping.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.updated_at IS 'Last update timestamp';


--
-- Name: COLUMN company_industry_benchmark_mapping.usable_for_operating_margin_benchmark; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.usable_for_operating_margin_benchmark IS 'Whether operating margin benchmark can be shown';


--
-- Name: COLUMN company_industry_benchmark_mapping.usable_for_revenue_benchmark; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_industry_benchmark_mapping.usable_for_revenue_benchmark IS 'Whether revenue benchmark can be shown';


--
-- Name: company_ntis_collaborative_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_ntis_collaborative_project (
    ntis_collaborative_project_id bigint NOT NULL,
    collaboration_country_name character varying(20),
    collaboration_participation_type_name character varying(20),
    collaborative_research_expense integer,
    collaborative_research_income integer,
    commissioned_research_fund integer,
    company_id integer,
    has_company_collaboration boolean,
    has_foreign_institute_collaboration boolean,
    has_other_collaboration boolean,
    has_public_institute_collaboration boolean,
    has_university_collaboration boolean,
    reference_date date,
    reference_year integer,
    research_performer_type_name character varying(20),
    research_type_name character varying(20),
    source_hash character varying(64) NOT NULL
);


--
-- Name: COLUMN company_ntis_collaborative_project.ntis_collaborative_project_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.ntis_collaborative_project_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_ntis_collaborative_project.collaboration_country_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.collaboration_country_name IS '공동연구참여국가명//예시) 대한민국';


--
-- Name: COLUMN company_ntis_collaborative_project.collaboration_participation_type_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.collaboration_participation_type_name IS '공동연구참여형태명//예시) 기타';


--
-- Name: COLUMN company_ntis_collaborative_project.collaborative_research_expense; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.collaborative_research_expense IS '위탁과제연구비//예시) 80000000';


--
-- Name: COLUMN company_ntis_collaborative_project.collaborative_research_income; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.collaborative_research_income IS '공동연구비수입금액//예시) 3000000';


--
-- Name: COLUMN company_ntis_collaborative_project.commissioned_research_fund; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.commissioned_research_fund IS '위탁과제연구비//예시) 67000000';


--
-- Name: COLUMN company_ntis_collaborative_project.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_ntis_collaborative_project.has_company_collaboration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.has_company_collaboration IS '기업공동연구여부//예시) N';


--
-- Name: COLUMN company_ntis_collaborative_project.has_foreign_institute_collaboration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.has_foreign_institute_collaboration IS '외국연구기관공동연구여부//예시) N';


--
-- Name: COLUMN company_ntis_collaborative_project.has_other_collaboration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.has_other_collaboration IS '기타공동연구여부//예시) N';


--
-- Name: COLUMN company_ntis_collaborative_project.has_public_institute_collaboration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.has_public_institute_collaboration IS '기업공동연구여부//예시) N';


--
-- Name: COLUMN company_ntis_collaborative_project.has_university_collaboration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.has_university_collaboration IS '기업공동연구여부//예시) N';


--
-- Name: COLUMN company_ntis_collaborative_project.reference_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.reference_date IS '기준일자//예시) 20220701';


--
-- Name: COLUMN company_ntis_collaborative_project.reference_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.reference_year IS '기준연도//예시) 2022';


--
-- Name: COLUMN company_ntis_collaborative_project.research_performer_type_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.research_performer_type_name IS '연구수행주체명//예시) 중소기업';


--
-- Name: COLUMN company_ntis_collaborative_project.research_type_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.research_type_name IS '연구형태명//예시) 위탁과제';


--
-- Name: COLUMN company_ntis_collaborative_project.source_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_collaborative_project.source_hash IS '원본 데이터 중복 방지를 위한 해시값';


--
-- Name: company_ntis_collaborative_pr_ntis_collaborative_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_ntis_collaborative_project ALTER COLUMN ntis_collaborative_project_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_ntis_collaborative_pr_ntis_collaborative_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_ntis_lead_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_ntis_lead_project (
    ntis_lead_project_id bigint NOT NULL,
    annual_research_end_date date,
    annual_research_start_date date,
    company_id integer,
    government_research_fund bigint,
    private_research_fund bigint,
    project_name character varying(1000),
    reference_date date,
    reference_year integer,
    region_name character varying(1000),
    science_technology_category_name character varying(1000),
    source_hash character varying(64) NOT NULL,
    supervising_ministry_name character varying(20),
    total_research_end_date date,
    total_research_fund bigint,
    total_research_start_date date
);


--
-- Name: COLUMN company_ntis_lead_project.ntis_lead_project_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.ntis_lead_project_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_ntis_lead_project.annual_research_end_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.annual_research_end_date IS '당해연구종료일//예시) 20221130';


--
-- Name: COLUMN company_ntis_lead_project.annual_research_start_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.annual_research_start_date IS '총연구종료일//예시) 20220201';


--
-- Name: COLUMN company_ntis_lead_project.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_ntis_lead_project.government_research_fund; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.government_research_fund IS '정부투자연구비//예시)  85,500,000';


--
-- Name: COLUMN company_ntis_lead_project.private_research_fund; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.private_research_fund IS '민간연구비합계//예시)  11,125,000';


--
-- Name: COLUMN company_ntis_lead_project.project_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.project_name IS 'NTIS사업명//예시) 농업실용화기술R&D지원';


--
-- Name: COLUMN company_ntis_lead_project.reference_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.reference_date IS '기준일자//예시) 20230101';


--
-- Name: COLUMN company_ntis_lead_project.reference_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.reference_year IS '기준연도//예시) 2022';


--
-- Name: COLUMN company_ntis_lead_project.region_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.region_name IS '지역구분명//예시) 부산광역시 강서구';


--
-- Name: COLUMN company_ntis_lead_project.science_technology_category_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.science_technology_category_name IS '과학기술표준분류명//예시) 농업 환경정화';


--
-- Name: COLUMN company_ntis_lead_project.source_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.source_hash IS '원본 데이터 중복 방지를 위한 해시값';


--
-- Name: COLUMN company_ntis_lead_project.supervising_ministry_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.supervising_ministry_name IS '주관부처명//예시) 농촌진흥청';


--
-- Name: COLUMN company_ntis_lead_project.total_research_end_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.total_research_end_date IS '총연구종료일/예시) 20221130';


--
-- Name: COLUMN company_ntis_lead_project.total_research_fund; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.total_research_fund IS '연구비합계//예시)  122,250,000';


--
-- Name: COLUMN company_ntis_lead_project.total_research_start_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_ntis_lead_project.total_research_start_date IS '총연구시작일//예시) 20220201';


--
-- Name: company_ntis_lead_project_ntis_lead_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_ntis_lead_project ALTER COLUMN ntis_lead_project_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_ntis_lead_project_ntis_lead_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_patent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_patent (
    patent_id bigint NOT NULL,
    application_date date,
    company_id integer,
    company_relation_code character varying(20),
    is_active boolean,
    patent_type character varying(20),
    registration_date date,
    registration_status character varying(20),
    source_hash character varying(64) NOT NULL
);


--
-- Name: COLUMN company_patent.patent_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.patent_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_patent.application_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.application_date IS '등록상태//예시) 20090220';


--
-- Name: COLUMN company_patent.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_patent.company_relation_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.company_relation_code IS '등록상태//예시) 본인';


--
-- Name: COLUMN company_patent.is_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.is_active IS '등록상태//예시) Y';


--
-- Name: COLUMN company_patent.patent_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.patent_type IS '특허권//예시) 특허권';


--
-- Name: COLUMN company_patent.registration_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.registration_date IS '등록상태//예시) 20110602';


--
-- Name: COLUMN company_patent.registration_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.registration_status IS '등록상태//예시) 등록';


--
-- Name: COLUMN company_patent.source_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent.source_hash IS '원본 데이터 중복 방지를 위한 해시값';


--
-- Name: company_patent_patent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_patent ALTER COLUMN patent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_patent_patent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_patent_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_patent_statistics (
    patent_statistics_id bigint NOT NULL,
    company_id integer,
    patent_application_count integer,
    registered_patent_count integer,
    year integer
);


--
-- Name: COLUMN company_patent_statistics.patent_statistics_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent_statistics.patent_statistics_id IS '시퀀스//이건 자동으로 채번되는 것';


--
-- Name: COLUMN company_patent_statistics.company_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent_statistics.company_id IS '기업일련번호//예시) 117';


--
-- Name: COLUMN company_patent_statistics.patent_application_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent_statistics.patent_application_count IS '특허출원건수//예시) 1';


--
-- Name: COLUMN company_patent_statistics.registered_patent_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent_statistics.registered_patent_count IS '특허등록건수//예시) 3';


--
-- Name: COLUMN company_patent_statistics.year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_patent_statistics.year IS '연도//예시) 2022';


--
-- Name: company_patent_statistics_patent_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_patent_statistics ALTER COLUMN patent_statistics_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_patent_statistics_patent_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industry_benchmark_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.industry_benchmark_index (
    industry_index_id bigint NOT NULL,
    availability_status character varying(50),
    base_year integer NOT NULL,
    bok_industry_code character varying(50) NOT NULL,
    calculation_type character varying(50),
    growth_rate numeric(24,10),
    index_value numeric(24,10),
    metric character varying(50) NOT NULL,
    source_id bigint NOT NULL,
    unavailable_reason character varying(100),
    year integer NOT NULL
);


--
-- Name: COLUMN industry_benchmark_index.industry_index_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.industry_index_id IS 'Industry benchmark index ID';


--
-- Name: COLUMN industry_benchmark_index.availability_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.availability_status IS 'Availability status';


--
-- Name: COLUMN industry_benchmark_index.base_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.base_year IS 'Base year for index calculation';


--
-- Name: COLUMN industry_benchmark_index.bok_industry_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.bok_industry_code IS 'BOK industry code';


--
-- Name: COLUMN industry_benchmark_index.calculation_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.calculation_type IS 'Calculation type: BASE_INDEX, CUMULATIVE_GROWTH';


--
-- Name: COLUMN industry_benchmark_index.growth_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.growth_rate IS 'Growth rate used to derive this index value';


--
-- Name: COLUMN industry_benchmark_index.index_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.index_value IS 'Index value, commonly 2021 = 100';


--
-- Name: COLUMN industry_benchmark_index.metric; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.metric IS 'Metric represented by the index, such as REVENUE';


--
-- Name: COLUMN industry_benchmark_index.source_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.source_id IS 'Source document ID';


--
-- Name: COLUMN industry_benchmark_index.unavailable_reason; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.unavailable_reason IS 'Reason when index is unavailable';


--
-- Name: COLUMN industry_benchmark_index.year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_index.year IS 'Observation year';


--
-- Name: industry_benchmark_index_industry_index_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.industry_benchmark_index ALTER COLUMN industry_index_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industry_benchmark_index_industry_index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industry_benchmark_metric; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.industry_benchmark_metric (
    benchmark_metric_id bigint NOT NULL,
    bok_industry_code character varying(50) NOT NULL,
    bok_industry_name character varying(200),
    data_status character varying(50),
    metric character varying(50) NOT NULL,
    raw_label character varying(500),
    release_version character varying(50),
    source_id bigint NOT NULL,
    unit character varying(20),
    value numeric(24,10),
    value_type character varying(50),
    year integer NOT NULL
);


--
-- Name: COLUMN industry_benchmark_metric.benchmark_metric_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.benchmark_metric_id IS 'Industry benchmark metric ID';


--
-- Name: COLUMN industry_benchmark_metric.bok_industry_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.bok_industry_code IS 'BOK industry code, such as C29, C31, J, ALL';


--
-- Name: COLUMN industry_benchmark_metric.bok_industry_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.bok_industry_name IS 'BOK industry name';


--
-- Name: COLUMN industry_benchmark_metric.data_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.data_status IS 'Data status: OBSERVED, MISSING, NOT_PUBLISHED';


--
-- Name: COLUMN industry_benchmark_metric.metric; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.metric IS 'Metric code: REVENUE_GROWTH_RATE, OPERATING_MARGIN';


--
-- Name: COLUMN industry_benchmark_metric.raw_label; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.raw_label IS 'Raw label from the source sheet or API item';


--
-- Name: COLUMN industry_benchmark_metric.release_version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.release_version IS 'Release version copied from the source';


--
-- Name: COLUMN industry_benchmark_metric.source_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.source_id IS 'Source document ID';


--
-- Name: COLUMN industry_benchmark_metric.unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.unit IS 'Unit: %, %P, INDEX';


--
-- Name: COLUMN industry_benchmark_metric.value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.value IS 'Metric value as published or parsed';


--
-- Name: COLUMN industry_benchmark_metric.value_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.value_type IS 'Value type: LEVEL, GROWTH_RATE, REFERENCE';


--
-- Name: COLUMN industry_benchmark_metric.year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_metric.year IS 'Observation year';


--
-- Name: industry_benchmark_metric_benchmark_metric_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.industry_benchmark_metric ALTER COLUMN benchmark_metric_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industry_benchmark_metric_benchmark_metric_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industry_benchmark_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.industry_benchmark_source (
    source_id bigint NOT NULL,
    file_hash character varying(64) NOT NULL,
    note text,
    observation_year integer,
    population character varying(200),
    published_at date,
    release_version character varying(50),
    release_year integer,
    source_name character varying(200) NOT NULL,
    source_type character varying(50) NOT NULL,
    source_url character varying(1000)
);


--
-- Name: COLUMN industry_benchmark_source.source_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.source_id IS 'Industry benchmark source ID';


--
-- Name: COLUMN industry_benchmark_source.file_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.file_hash IS 'Hash of the downloaded source file for deduplication';


--
-- Name: COLUMN industry_benchmark_source.note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.note IS 'Source notes and collection caveats';


--
-- Name: COLUMN industry_benchmark_source.observation_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.observation_year IS 'Year measured by the source data';


--
-- Name: COLUMN industry_benchmark_source.population; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.population IS 'Survey population, such as audited non-financial corporations';


--
-- Name: COLUMN industry_benchmark_source.published_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.published_at IS 'Official publication date';


--
-- Name: COLUMN industry_benchmark_source.release_version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.release_version IS 'Release version: PRELIMINARY or FINAL';


--
-- Name: COLUMN industry_benchmark_source.release_year; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.release_year IS 'Year when the source was released';


--
-- Name: COLUMN industry_benchmark_source.source_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.source_name IS 'Source document name, such as BOK 2025 preliminary business analysis';


--
-- Name: COLUMN industry_benchmark_source.source_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.source_type IS 'Source type: BOK_ECOS, BOK_RELEASE_XLSX, BOK_RELEASE_PDF';


--
-- Name: COLUMN industry_benchmark_source.source_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.industry_benchmark_source.source_url IS 'Official source URL';


--
-- Name: industry_benchmark_source_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.industry_benchmark_source ALTER COLUMN source_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industry_benchmark_source_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ksic_bok_industry_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ksic_bok_industry_mapping (
    mapping_id bigint NOT NULL,
    bok_industry_code character varying(50),
    bok_industry_name character varying(200),
    confidence_reason text,
    ksic_code character varying(20) NOT NULL,
    ksic_division_code character varying(10),
    ksic_name character varying(500),
    ksic_section_code character varying(10),
    mapping_level character varying(50),
    mapping_status character varying(50),
    reviewed_at timestamp(6) without time zone,
    reviewed_by character varying(100)
);


--
-- Name: COLUMN ksic_bok_industry_mapping.mapping_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.mapping_id IS 'KSIC to BOK industry mapping ID';


--
-- Name: COLUMN ksic_bok_industry_mapping.bok_industry_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.bok_industry_code IS 'Mapped BOK industry code, such as C29';


--
-- Name: COLUMN ksic_bok_industry_mapping.bok_industry_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.bok_industry_name IS 'Mapped BOK industry name';


--
-- Name: COLUMN ksic_bok_industry_mapping.confidence_reason; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.confidence_reason IS 'Reason for confidence level or ambiguity';


--
-- Name: COLUMN ksic_bok_industry_mapping.ksic_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.ksic_code IS 'KSIC code from KODATA, such as C29199';


--
-- Name: COLUMN ksic_bok_industry_mapping.ksic_division_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.ksic_division_code IS 'KSIC division code, such as 29';


--
-- Name: COLUMN ksic_bok_industry_mapping.ksic_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.ksic_name IS 'KSIC industry name';


--
-- Name: COLUMN ksic_bok_industry_mapping.ksic_section_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.ksic_section_code IS 'KSIC section code, such as C';


--
-- Name: COLUMN ksic_bok_industry_mapping.mapping_level; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.mapping_level IS 'Mapping level: EXACT, DIVISION, SECTION, PROXY, UNAVAILABLE';


--
-- Name: COLUMN ksic_bok_industry_mapping.mapping_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.mapping_status IS 'Mapping status: CONFIRMED, PENDING_REVIEW, AMBIGUOUS, UNAVAILABLE';


--
-- Name: COLUMN ksic_bok_industry_mapping.reviewed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.reviewed_at IS 'Review timestamp';


--
-- Name: COLUMN ksic_bok_industry_mapping.reviewed_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ksic_bok_industry_mapping.reviewed_by IS 'Reviewer identifier';


--
-- Name: ksic_bok_industry_mapping_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ksic_bok_industry_mapping ALTER COLUMN mapping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ksic_bok_industry_mapping_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ksic_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ksic_info (
    ksic_code character varying(20) NOT NULL,
    industry_description text
);


--
-- Name: btp_equipment btp_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_equipment
    ADD CONSTRAINT btp_equipment_pkey PRIMARY KEY (id);


--
-- Name: btp_support_history btp_support_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_support_history
    ADD CONSTRAINT btp_support_history_pkey PRIMARY KEY (support_history_id);


--
-- Name: btp_support_program btp_support_program_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_support_program
    ADD CONSTRAINT btp_support_program_pkey PRIMARY KEY (support_program_id);


--
-- Name: company_business_purpose company_business_purpose_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_business_purpose
    ADD CONSTRAINT company_business_purpose_pkey PRIMARY KEY (business_purpose_id);


--
-- Name: company_employment_statistics company_employment_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_employment_statistics
    ADD CONSTRAINT company_employment_statistics_pkey PRIMARY KEY (employment_statistics_id);


--
-- Name: company_financial_statistics company_financial_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_financial_statistics
    ADD CONSTRAINT company_financial_statistics_pkey PRIMARY KEY (financial_statistics_id);


--
-- Name: company_industry_benchmark_mapping company_industry_benchmark_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_industry_benchmark_mapping
    ADD CONSTRAINT company_industry_benchmark_mapping_pkey PRIMARY KEY (company_id);


--
-- Name: company_ntis_collaborative_project company_ntis_collaborative_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_collaborative_project
    ADD CONSTRAINT company_ntis_collaborative_project_pkey PRIMARY KEY (ntis_collaborative_project_id);


--
-- Name: company_ntis_lead_project company_ntis_lead_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_lead_project
    ADD CONSTRAINT company_ntis_lead_project_pkey PRIMARY KEY (ntis_lead_project_id);


--
-- Name: company_patent company_patent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent
    ADD CONSTRAINT company_patent_pkey PRIMARY KEY (patent_id);


--
-- Name: company_patent_statistics company_patent_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent_statistics
    ADD CONSTRAINT company_patent_statistics_pkey PRIMARY KEY (patent_statistics_id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (company_id);


--
-- Name: industry_benchmark_index industry_benchmark_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_index
    ADD CONSTRAINT industry_benchmark_index_pkey PRIMARY KEY (industry_index_id);


--
-- Name: industry_benchmark_metric industry_benchmark_metric_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_metric
    ADD CONSTRAINT industry_benchmark_metric_pkey PRIMARY KEY (benchmark_metric_id);


--
-- Name: industry_benchmark_source industry_benchmark_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_source
    ADD CONSTRAINT industry_benchmark_source_pkey PRIMARY KEY (source_id);


--
-- Name: ksic_bok_industry_mapping ksic_bok_industry_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ksic_bok_industry_mapping
    ADD CONSTRAINT ksic_bok_industry_mapping_pkey PRIMARY KEY (mapping_id);


--
-- Name: ksic_info ksic_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ksic_info
    ADD CONSTRAINT ksic_info_pkey PRIMARY KEY (ksic_code);


--
-- Name: btp_equipment uk_btp_equipment_source_seq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_equipment
    ADD CONSTRAINT uk_btp_equipment_source_seq UNIQUE (source_equipment_seq);


--
-- Name: btp_support_history uk_btp_support_history_source_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_support_history
    ADD CONSTRAINT uk_btp_support_history_source_hash UNIQUE (source_hash);


--
-- Name: btp_support_program uk_btp_support_program_year_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_support_program
    ADD CONSTRAINT uk_btp_support_program_year_code UNIQUE (program_year, code);


--
-- Name: company_business_purpose uk_company_business_purpose_company_display_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_business_purpose
    ADD CONSTRAINT uk_company_business_purpose_company_display_order UNIQUE (company_id, display_order);


--
-- Name: company_employment_statistics uk_company_employment_statistics_company_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_employment_statistics
    ADD CONSTRAINT uk_company_employment_statistics_company_year UNIQUE (company_id, year);


--
-- Name: company_financial_statistics uk_company_financial_statistics_company_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_financial_statistics
    ADD CONSTRAINT uk_company_financial_statistics_company_year UNIQUE (company_id, year);


--
-- Name: company_ntis_collaborative_project uk_company_ntis_collaborative_project_source_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_collaborative_project
    ADD CONSTRAINT uk_company_ntis_collaborative_project_source_hash UNIQUE (source_hash);


--
-- Name: company_ntis_lead_project uk_company_ntis_lead_project_source_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_lead_project
    ADD CONSTRAINT uk_company_ntis_lead_project_source_hash UNIQUE (source_hash);


--
-- Name: company_patent uk_company_patent_source_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent
    ADD CONSTRAINT uk_company_patent_source_hash UNIQUE (source_hash);


--
-- Name: company_patent_statistics uk_company_patent_statistics_company_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent_statistics
    ADD CONSTRAINT uk_company_patent_statistics_company_year UNIQUE (company_id, year);


--
-- Name: industry_benchmark_index uk_industry_benchmark_index_source_industry_metric_base_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_index
    ADD CONSTRAINT uk_industry_benchmark_index_source_industry_metric_base_year UNIQUE (source_id, bok_industry_code, metric, base_year, year);


--
-- Name: industry_benchmark_metric uk_industry_benchmark_metric_source_industry_metric_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_metric
    ADD CONSTRAINT uk_industry_benchmark_metric_source_industry_metric_year UNIQUE (source_id, bok_industry_code, metric, year);


--
-- Name: industry_benchmark_source uk_industry_benchmark_source_file_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_benchmark_source
    ADD CONSTRAINT uk_industry_benchmark_source_file_hash UNIQUE (file_hash);


--
-- Name: ksic_bok_industry_mapping uk_ksic_bok_industry_mapping_ksic; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ksic_bok_industry_mapping
    ADD CONSTRAINT uk_ksic_bok_industry_mapping_ksic UNIQUE (ksic_code);


--
-- Name: idx_btp_support_history_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_btp_support_history_code ON public.btp_support_history USING btree (code);


--
-- Name: idx_btp_support_history_company_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_btp_support_history_company_year ON public.btp_support_history USING btree (company_id, support_year);


--
-- Name: idx_btp_support_history_selected_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_btp_support_history_selected_date ON public.btp_support_history USING btree (selected_date);


--
-- Name: idx_company_business_purpose_company_display_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_business_purpose_company_display_order ON public.company_business_purpose USING btree (company_id, display_order);


--
-- Name: idx_company_employment_statistics_company_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_employment_statistics_company_year ON public.company_employment_statistics USING btree (company_id, year);


--
-- Name: idx_company_financial_statistics_company_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_financial_statistics_company_year ON public.company_financial_statistics USING btree (company_id, year);


--
-- Name: idx_company_industry_benchmark_mapping_bok; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_industry_benchmark_mapping_bok ON public.company_industry_benchmark_mapping USING btree (bok_industry_code);


--
-- Name: idx_company_industry_benchmark_mapping_ksic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_industry_benchmark_mapping_ksic ON public.company_industry_benchmark_mapping USING btree (ksic_code);


--
-- Name: idx_company_industry_benchmark_mapping_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_industry_benchmark_mapping_status ON public.company_industry_benchmark_mapping USING btree (mapping_status);


--
-- Name: idx_company_ntis_collaborative_project_company_reference_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_ntis_collaborative_project_company_reference_year ON public.company_ntis_collaborative_project USING btree (company_id, reference_year);


--
-- Name: idx_company_ntis_lead_project_company_reference_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_ntis_lead_project_company_reference_year ON public.company_ntis_lead_project USING btree (company_id, reference_year);


--
-- Name: idx_company_patent_company_registration_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_patent_company_registration_date ON public.company_patent USING btree (company_id, registration_date);


--
-- Name: idx_company_patent_statistics_company_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_patent_statistics_company_year ON public.company_patent_statistics USING btree (company_id, year);


--
-- Name: idx_industry_benchmark_index_industry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_index_industry ON public.industry_benchmark_index USING btree (bok_industry_code, year);


--
-- Name: idx_industry_benchmark_index_metric; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_index_metric ON public.industry_benchmark_index USING btree (metric, base_year);


--
-- Name: idx_industry_benchmark_index_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_index_source ON public.industry_benchmark_index USING btree (source_id);


--
-- Name: idx_industry_benchmark_metric_industry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_metric_industry ON public.industry_benchmark_metric USING btree (bok_industry_code, year);


--
-- Name: idx_industry_benchmark_metric_metric; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_metric_metric ON public.industry_benchmark_metric USING btree (metric, year);


--
-- Name: idx_industry_benchmark_metric_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_metric_source ON public.industry_benchmark_metric USING btree (source_id);


--
-- Name: idx_industry_benchmark_source_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_source_type ON public.industry_benchmark_source USING btree (source_type, release_version);


--
-- Name: idx_industry_benchmark_source_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_industry_benchmark_source_year ON public.industry_benchmark_source USING btree (release_year, observation_year);


--
-- Name: idx_ksic_bok_industry_mapping_bok; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ksic_bok_industry_mapping_bok ON public.ksic_bok_industry_mapping USING btree (bok_industry_code);


--
-- Name: idx_ksic_bok_industry_mapping_ksic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ksic_bok_industry_mapping_ksic ON public.ksic_bok_industry_mapping USING btree (ksic_code);


--
-- Name: idx_ksic_bok_industry_mapping_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ksic_bok_industry_mapping_status ON public.ksic_bok_industry_mapping USING btree (mapping_status);


--
-- Name: company_patent fk3lygimi68ad4ddnksf2kfv60v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent
    ADD CONSTRAINT fk3lygimi68ad4ddnksf2kfv60v FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_patent_statistics fk4bystbih32wy2885f28ufssxo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_patent_statistics
    ADD CONSTRAINT fk4bystbih32wy2885f28ufssxo FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_ntis_lead_project fkecggh0fbhdr66h8x3juh8x4kh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_lead_project
    ADD CONSTRAINT fkecggh0fbhdr66h8x3juh8x4kh FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_employment_statistics fkfvf8sbgwvfvj7n32idrii35vt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_employment_statistics
    ADD CONSTRAINT fkfvf8sbgwvfvj7n32idrii35vt FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: btp_support_history fkfw0jbm0gpxpf9pegsl4l39v7n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.btp_support_history
    ADD CONSTRAINT fkfw0jbm0gpxpf9pegsl4l39v7n FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_financial_statistics fkibxlw7df0yq90kf184gbjec3j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_financial_statistics
    ADD CONSTRAINT fkibxlw7df0yq90kf184gbjec3j FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_ntis_collaborative_project fkkw0c7yqwy59q8ehn627gg34uv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_ntis_collaborative_project
    ADD CONSTRAINT fkkw0c7yqwy59q8ehn627gg34uv FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: company_business_purpose fkl9v93rr78cxx1e3u6d1bk11u7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_business_purpose
    ADD CONSTRAINT fkl9v93rr78cxx1e3u6d1bk11u7 FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- PostgreSQL database dump complete
--
