-- Deactivate generic Korean particles, administrative words, and KSIC boilerplate
-- terms that create noisy BTP equipment/support-program matches.
with low_quality_keyword(keyword, reason) as (
    values
        ('가능한', 'generic predicate'),
        ('갖춘', 'generic predicate'),
        ('것을', 'generic phrase'),
        ('관련', 'generic relation'),
        ('관련된', 'generic relation'),
        ('관한', 'generic relation'),
        ('관리하는', 'generic verb'),
        ('구성', 'generic structure'),
        ('구성품', 'generic structure'),
        ('근교지역으로', 'generic region phrase'),
        ('기타', 'classification boilerplate'),
        ('기업', 'administrative word'),
        ('달리', 'classification boilerplate'),
        ('대상', 'administrative word'),
        ('대상으로', 'administrative word'),
        ('대한', 'generic relation'),
        ('등과', 'generic connector'),
        ('등에', 'generic connector'),
        ('등으로', 'generic connector'),
        ('또는', 'generic connector'),
        ('물품', 'generic object'),
        ('방식', 'generic method'),
        ('보관', 'generic activity'),
        ('부수적으로', 'classification boilerplate'),
        ('분류되지', 'classification boilerplate'),
        ('사업', 'administrative word'),
        ('사용', 'generic activity'),
        ('사용하는', 'generic verb'),
        ('서비스', 'generic service word'),
        ('서비스를', 'generic service word'),
        ('서비스업', 'generic service word'),
        ('생산', 'generic activity'),
        ('생산하는', 'generic verb'),
        ('설치', 'generic activity'),
        ('시설', 'generic facility word'),
        ('아닌', 'generic predicate'),
        ('않는', 'generic predicate'),
        ('없는', 'generic predicate'),
        ('용도', 'generic purpose'),
        ('위해', 'generic purpose'),
        ('유지', 'generic activity'),
        ('의한', 'generic relation'),
        ('의해', 'generic relation'),
        ('이상', 'generic threshold'),
        ('이상의', 'generic threshold'),
        ('이용한', 'generic activity'),
        ('이용하여', 'generic activity'),
        ('이외', 'generic exclusion'),
        ('이하', 'generic threshold'),
        ('있는', 'generic predicate'),
        ('있다', 'generic predicate'),
        ('일반', 'generic adjective'),
        ('장착', 'generic attachment'),
        ('전용', 'generic purpose'),
        ('제공', 'generic activity'),
        ('제공하는', 'generic verb'),
        ('제품', 'generic product word'),
        ('제품을', 'generic product word'),
        ('제외한', 'classification boilerplate'),
        ('제조', 'generic manufacturing word'),
        ('제조업', 'generic manufacturing word'),
        ('주로', 'generic adverb'),
        ('지역', 'generic region word'),
        ('지원', 'administrative word'),
        ('직접', 'generic adverb'),
        ('초과', 'generic threshold'),
        ('특정', 'generic adjective'),
        ('통해', 'generic relation'),
        ('따라', 'generic relation'),
        ('활동', 'generic activity'),
        ('형태의', 'generic form'),
        ('해당', 'generic reference'),
        ('함께', 'generic connector'),
        ('같은', 'generic connector'),
        ('단순', 'generic adjective'),
        ('공급', 'generic activity'),
        ('공급하는', 'generic verb'),
        ('산업', 'generic industry word'),
        ('산업용', 'generic industry word'),
        ('산업활동을', 'KSIC description boilerplate'),
        ('산업활동으로', 'KSIC description boilerplate'),
        ('산업활동으로서', 'KSIC description boilerplate'),
        ('산업활동도', 'KSIC description boilerplate'),
        ('독립적으로', 'generic adverb')
)
update public.btp_connection_keyword_rule rule
set active = false
from low_quality_keyword bad
where rule.keyword = bad.keyword
  and rule.active = true;
